### ISSUE TITLE
Make sources for sprite_download.png available, and/or add .tar.bz2

### ISSUE THREAD

**Issue by fingolfin** [jasoncostello/slate#6]
In my project, I don't offer .zip downloads, but rather .tar.gz and .tar.bz2. So I wanted to modify sprite_download.png accordingly. But its content is rather low-res and "fuzzy" (due to aliasing artifacts), and I don't know which font was used...

It would be nice if there was a way to do this cleanly, e.g. by having a high-res version of the folder symbol, without text, and info about the font, to compose them. Having a Photoshop/Gimp/whatever version of this with layers would also work...

Any chance you could make something like this available? Alternatively, just having a version with .tar.gz and .tar.bz2 instead of .tar.gz and .zip would help me. (Though hypothetically, other people might wish to use other formats, too).

Anyway, thank you for this nice them!

**Comment by brntbeer** [comment]
@fingolfin would having something in the [releases](https://github.com/jasoncostello/slate/releases) section for a new downloadable copy that included high-res versions of the images be a good middle ground? 

To get an idea of how these extra assets work, take a look at some of the downloads of the Atom Repo: https://github.com/atom/atom/releases/tag/v0.188.0. There's just extra items that you can attach to releases, and i think your high-res image would fit here!

**Comment by jasoncostello** [comment]
Or I'll just replace these with SVGs tonight :grin:

Sorry to be a slackerrrr

**Comment by jasoncostello** [comment]
This is no longer relevant in the new version of the layout.
